# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install npm
        env:
          NODE_AUTH_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWFsX2dyb3VwcyI6WyJob2xpc3RpY3MiLCIkYWxsIiwiJGF1dGhlbnRpY2F0ZWQiLCJAYWxsIiwiQGF1dGhlbnRpY2F0ZWQiLCJhbGwiXSwibmFtZSI6ImhvbGlzdGljcyIsImdyb3VwcyI6WyJob2xpc3RpY3MiLCIkYWxsIiwiJGF1dGhlbnRpY2F0ZWQiLCJAYWxsIiwiQGF1dGhlbnRpY2F0ZWQiLCJhbGwiLCIkYWxsIiwiJGF1dGhlbnRpY2F0ZWQiLCJAYWxsIiwiQGF1dGhlbnRpY2F0ZWQiLCJhbGwiLCJob2xpc3RpY3MiLCIkYWxsIiwiJGF1dGhlbnRpY2F0ZWQiLCJAYWxsIiwiQGF1dGhlbnRpY2F0ZWQiLCJhbGwiXSwiaWF0IjoxNjE0ODU2MDY1LCJuYmYiOjE2MTQ4NTYwNjYsImV4cCI6MTYyMDA0MDA2NX0.iBFbqDAVqL0seoALIIkkxcVo5a5QABMVgOP_YmDyF4g

        run: npm install dbdocs --registry=https://npm-staging.dbml.org/
        
      - name: check dbdocs
        run: dbdocs
      
      - name: build updated dbdocs
        env:
          DBDOCS_TOKEN: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlRlYU5ndXllbiIsInRva2VuIjoiMDBmMzI3ZjM2MmU0MjgwNjVjOTNhYTA3NWJhYmZhM2MiLCJpYXQiOjE2MTQ4NTcxNTV9.OONaJZkVsjLxTXY6inzr9NVl_UHSmXpAJEYUGRlaQMg

        run: dbdocs build ./ecommerceDBML.dbml
        
